### PR TITLE
Use readline to manage the prompt

### PR DESCRIPTION
**Pull request by MiLk**
- Use arrows to navigate in the history
- Standard movements commands are available (C-a, C-e, C-l, ...)
- Standard killing commands are available (C-k, C-w, ...)

See http://cnswww.cns.cwru.edu/php/chet/readline/readline.html

### CODE REVIEW

**Comment by stelcheck** [comment]
Nice :) Ill play with it a bit and merge it if all is good.

**Comment by stelcheck** [comment]
Color prompt might be giving you a bug here.
1. Run a command
2. arrow up
3. arrow down
4. arrow up

screen shot 2014-07-23 at 1 51 48 pm

**Comment by stelcheck** [comment]
Tried to use what is discussed here, to no avail: http://stackoverflow.com/questions/9468435/look-how-to-fix-column-calculation-in-python-readline-if-use-color-prompt

**Comment by MiLk** [comment]
Although I added RL_PROMPT_START_IGNORE and RL_PROMPT_END_IGNORE, it doesn't seem to change anything.

**Comment by MiLk** [comment]
The history is something I really want to see in `magecli`.
As nothing I tried with readline and colors works, I tried to use https://github.com/antirez/linenoise

After a quick patch, it supports color prompt and history: https://github.com/MiLk/linenoise/tree/features/color-prompt

But it's not as complete as readline.
No ctrl+r, ctrl+k, ctrl+a, ctrl+e, ...

I suggest to keep readline, but remove the color.
What do you think?

I'll try to compile on CentOS to be sure, it's not related to the readline version shipped with OSX.

**Comment by MiLk** [comment]
On CentOS, it works fine with readline 6.0

**Comment by stelcheck** [comment]
If nothing will do, color on the prompt can go but... its a bit too bad :/

**Comment by MiLk** [comment]
Problem fixed with GNU readline on OSX.
Readme updated.

**Comment by stelcheck** [comment]
``` bash
> ./bin/magecli -a game -d 172.16.13.2
Connecting to application game@172.16.13.2
Starting the MAGE CLI interactive prompt. Press CTRl+C to exit
Usage: [usercommand.command] [JSON object]

mage> user.register
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Type is not convertible to string
```

**Comment by MiLk** [comment]
Did you `make clean` before, in case you tried another branch before?

**Comment by stelcheck** [comment]
Yes.

**Comment by MiLk** [comment]
I tried the following, but I was not able to reproduce the issue:

```
mage> test.test
test.test error: test
mage> test.test ["ok"]
test.test:

{
    "response" : "test"
}

mage> test.test ["ok","lala"]
RPC error: MAGE RPC error: INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised: Too many parameters provided.
mage> test.test {"test":"test"}
test.test error: test
```

The exception comes from here:
https://github.com/cinemast/libjson-rpc-cpp/blob/master/src/jsonrpc/json/json_value.cpp#L700

What does your server return?

**Comment by stelcheck** [comment]
Ah, seems unrelated to this PR...

```
{
    "errorCode" :
    {
        "actual" : "undefined",
        "expected" : "string",
        "message" : "invalidPassword",
        "name" : "AssertionError",
        "operator" : "=="
    }
}
```

The library expects the error code to be a string... I will open an issue for this.

**Pull request merged**
