### PR TITLE
Update libjson-rpc-cpp

### PR DESCRIPTION
**Pull request by MiLk**
See #14 and https://github.com/cinemast/libjson-rpc-cpp/pull/50

### CODE REVIEW

**Comment by MiLk** [comment]
Please verify that it compiles before merging it.

I've updated https://github.com/mage/mage-sdk-cpp/pull/10

**Comment by MiLk** [comment]
Compiles on OSX 10.9.4 with Apple LLVM version 5.1 (clang-503.0.40)

**Comment by stelcheck** [comment]
I'll give it a shot now.

**Comment by stelcheck** [comment]
LGTM

**Pull request merged**
