### PR TITLE
Add const keyword, use references, coding style

### PR DESCRIPTION
**Pull request by MiLk**
- Methods which don't change an attribute should be set as `const`.
- Pass arguments by reference to avoid copy.
- Line length: 80.

### CODE REVIEW

**Comment by ronkorving** [comment]
lgtm

**Comment by MiLk** [comment]
@stelcheck Please wait before merging it.
I'll make some changes on contents added by #20

**Comment by stelcheck** [comment]
Could you get this done soon? Would like to make a release.

**Comment by MiLk** [comment]
Looks better. There is still something I want to do with `MageSuccess`.

I use [hungarian notation](http://en.wikipedia.org/wiki/Hungarian_notation) for attributes naming.

**Comment by MiLk** [comment]
Should `MageError` be an abstract class? It will no longer be possible to instantiate directly a `MageError`, only its children.

Are you ok with the hungarian notation? If so, I will update all the attributes.

For `MageSuccess`, I think we will have to leave it as it is for now.

**Comment by stelcheck** [comment]
I am fine with leaving MageError as it is for now. 

I have no strong feeling about the notation used, as long as it is mentioned in the README and that you provide a link that points to some reference. 

MageSuccess is an odd one... but yes, I see no other way around it :/

**Comment by MiLk** [comment]
I added the [Google cpp linter](http://google-styleguide.googlecode.com/svn/trunk/cpplint/cpplint.py).
I've done all the changes I wanted to do.

**Comment by stelcheck** [comment]
Examples were not linted, and there were still minor lint errors which I am currently fixing. Will merge soon. 

Good work!

**Pull request merged**
