### PR TITLE
Android

### PR DESCRIPTION
**Pull request by stelcheck**
@ronkorving @aogilvie @AlmirKadric please feel free to review comment.

P.S: Still have very little idea of what I am doing. Feel free to question anything I do.

### CODE REVIEW

**Comment by stelcheck** [comment]
For some reason, when I try to build it I get vtable errors - as if the actual object files were not present. I am starting to think I am doing something wrong in this PR.

**Comment by ronkorving** [comment]
If you need cURL, you can probably submodule https://github.com/bagder/curl ?

**Comment by stelcheck** [comment]
I am trying to avoid to compile or adapt cURL for all the different platforms I am aiming to support at the moment. What I use here, as (iirc) describe in the README is what cocos2dx gives you as external, so it is ios/android/wp ready. I don't know if this is really the best way to do it, but it sure is a time saver for now to be able to use prebuilts I can trust.

**Comment by stelcheck** [comment]
Was building as a shared library until now, but for some reason was getting the following error on application startup:

```
E/Trace   (26627): error opening trace file: No such file or directory (2)
E/dalvikvm(26627): dlopen("/data/app-lib/org.cocos2dx.hellocpp-1/libcocos2dcpp.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1665): could not load library "libmage.so" needed by "libcocos2dcpp.so"; caused by load_library(linker.cpp:750): library "libmage.so" not found
E/EmbeddedLogger(  576): App crashed! Process: org.cocos2dx.hellocpp
E/EmbeddedLogger(  576): App crashed! Package: org.cocos2dx.hellocpp v1 (1.0)
E/EmbeddedLogger(  576): Application Label: mage-sdk-cpp-cocos2dx
E/AndroidRuntime(26627): FATAL EXCEPTION: main
E/AndroidRuntime(26627): java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1665): could not load library "libmage.so" needed by "libcocos2dcpp.so"; caused by load_library(linker.cpp:750): library "libmage.so" not found
E/AndroidRuntime(26627):    at java.lang.Runtime.loadLibrary(Runtime.java:371)
E/AndroidRuntime(26627):    at java.lang.System.loadLibrary(System.java:535)
E/AndroidRuntime(26627):    at org.cocos2dx.lib.Cocos2dxActivity.onLoadNativeLibraries(Cocos2dxActivity.java:68)
E/AndroidRuntime(26627):    at org.cocos2dx.lib.Cocos2dxActivity.onCreate(Cocos2dxActivity.java:87)
E/AndroidRuntime(26627):    at android.app.Activity.performCreate(Activity.java:5165)
E/AndroidRuntime(26627):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1103)
E/AndroidRuntime(26627):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
E/AndroidRuntime(26627):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
E/AndroidRuntime(26627):    at android.app.ActivityThread.access$600(ActivityThread.java:162)
E/AndroidRuntime(26627):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1366)
E/AndroidRuntime(26627):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(26627):    at android.os.Looper.loop(Looper.java:158)
E/AndroidRuntime(26627):    at android.app.ActivityThread.main(ActivityThread.java:5751)
E/AndroidRuntime(26627):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(26627):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(26627):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
E/AndroidRuntime(26627):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
E/AndroidRuntime(26627):    at dalvik.system.NativeStart.main(Native Method)
```

The cocos2dx build script output seem to say that it was indeed packaging it. Anyway, got tired of this, and instead now I build it as a static lib (which is what we do for the OS X - and later linux, windows I guess - versions anyway). A few more steps to get to build, but now works as expected on Android.

**Comment by aogilvie** [comment]
I tried `make android`

output: 

```
|| mage-sdk-cpp: open .
|| mage-sdk-cpp: make android
cd platforms/android && /Applications/Xcode.app/Contents/Developer/usr/bin/make
NDK_PROJECT_PATH=/Users/Ally/Documents/Wizcorp/mage-sdk-cpp/platforms/android /Users/Ally/Documents/android-ndk-r9d/ndk-build
Android NDK: WARNING:/Users/Ally/Documents/Wizcorp/mage-sdk-cpp/platforms/android/jni/Android.mk:mage-sdk: LOCAL_LDFLAGS is always ignored for static libraries    
Android NDK: WARNING:/Users/Ally/Documents/Wizcorp/mage-sdk-cpp/platforms/android/jni/Android.mk:mage-sdk: LOCAL_LDLIBS is always ignored for static libraries    
Android NDK: WARNING:/Users/Ally/Documents/Wizcorp/mage-sdk-cpp/platforms/android/jni/Android.mk:mage-sdk: non-system libraries in linker flags: /Users/Ally/Documents/Wizcorp/mage-sdk-cpp/platforms/android/jni/../../externals/curl/prebuilt/android/armeabi/libcurl.a    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
make[2]: Entering directory `/Users/Ally/Documents/Wizcorp/mage-sdk-cpp/platforms/android'
[armeabi] Compile++ thumb: mage-sdk <= exceptions.cpp
[armeabi] Compile++ thumb: mage-sdk <= mage.cpp
In file included from /Users/Ally/Documents/Wizcorp/mage-sdk-cpp/platforms/android/jni/../../../src/mage.cpp:1:0:
/Users/Ally/Documents/Wizcorp/mage-sdk-cpp/platforms/android/jni/../../../src/mage.h:7:25: fatal error: jsonrpc/rpc.h: No such file or directory
compilation terminated.
make[2]: *** [/Users/Ally/Documents/Wizcorp/mage-sdk-cpp/platforms/android/obj/local/armeabi/objs/mage-sdk//Users/Ally/Documents/Wizcorp/mage-sdk-cpp/platforms/android/jni/__/__/__/src/mage.o] Error 1
make[2]: Leaving directory `/Users/Ally/Documents/Wizcorp/mage-sdk-cpp/platforms/android'
make[1]: *** [all] Error 2
make: *** [android] Error 2
|| mage-sdk-cpp: 
|| mage-sdk-cpp: 
|| mage-sdk-cpp: 
```

**Comment by stelcheck** [comment]
Did you git submodule update --init ?

**Pull request merged**
