### PR TITLE
Delete httpClient only once.

### PR DESCRIPTION
**Pull request by tokutake**
httpClient is deleted in jsonrpc::Client destructor. So, mage::RPC does not need to delete httpClient in it's destructor.

### CODE REVIEW

**Comment by stelcheck** [comment]
@MiLk could you confirm?

**Comment by MiLk** [comment]
Yes, but it's a bad behaviour.

I'd prefer to open a PR on libjson-rpc-cpp, because you should not delete something you didn't allocate.
That's why I didn't check it before :/

**Comment by stelcheck** [comment]
I'll leave this open then; @MiLk could you maybe make an issue referencing this one on libjson-rpc-cpp?

**Comment by stelcheck** [comment]
This should now be done properly, closing.

**Pull request closed without merging**
