### PR TITLE
CMake

### PR DESCRIPTION
**Pull request by MiLk**
Use cmake to generate the Makefile.

Tested with:
- Ubuntu 13.04, cmake 2.8.10.1, gcc 4.7.3.
- CentOS 6.5, cmake 2.8.8, gcc 4.8.2 using [Red Hat developer toolset](https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/2/html/User_Guide/sect-Red_Hat_Developer_Toolset-Install.html) and `devtoolset-2-gcc devtoolset-2-gcc-c++ devtoolset-2-libstdc++-devel`.
- OSX 10.9.4, cmake 3.0.0, Apple LLVM version 5.1 (clang-503.0.40).

### CODE REVIEW

**Comment by stelcheck** [comment]
I'll need some time to play with this, unless I get a person or two :+1 'ing it

**Comment by MiLk** [comment]
Updated.

Tested again on:
- CentOS 6.5, cmake 2.8.8, gcc 4.8.2.
- OSX 10.9.4, cmake 3.0.0, Apple LLVM version 5.1 (clang-503.0.40).

**Comment by stelcheck** [comment]
Looks very good. Some paths seem to be changing (now being prefixed with ./build); is it possible that it will end up breaking some other peoples code/setup?

**Comment by MiLk** [comment]
For custom targets (iOS, Android), the files will still be at the same place.
Except the extra step to generate the Makefile, it should not break anything.

For other targets, all the files are now in the build directory (it can be anywhere you want even outside the repo directory).

**Comment by stelcheck** [comment]
No, in this case I think it would be fine.

**Pull request merged**
